name: isohttpd
description: A lightweight http server that runs in an isolate. Router and logs are included.
version: 0.5.0
homepage: https://github.com/synw/isohttpd

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.5

dependencies:
  pedantic: ^1.11.1
  extra_pedantic: ^1.5.0
  meta: ^1.8.0
  body_parser: ^1.1.1
  iso: ^1.0.0
  path: ^1.8.2
  emodebug: ^0.5.0
