name: isohttpd
description: A lightweight http server that runs in an isolate. Router and logs are included.
version: 0.3.0
homepage: https://github.com/synw/isohttpd
author: synw <ansterj@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dev_dependencies:
  test: ^1.6.5

dependencies:
  pedantic: ^1.8.0+1
  extra_pedantic: ^1.1.1+3
  meta: ^1.1.8
  body_parser: ^1.1.1
  iso: ^0.3.0
  path: ^1.6.4
  emodebug:
    path: ../emodebug
